//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class authors
    {
        public int forfatterID { get; set; }
        public string cristinID { get; set; }
        public string forskningsID { get; set; }
        public int institusjonsID { get; set; }
        public double poeng { get; set; }
        public double poengNytt { get; set; }
    }
}
