//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class forskning
    {
        public int resultatID { get; set; }
        public string forskningsID { get; set; }
        public string tittel { get; set; }
        public string aar { get; set; }
        public string kvalitet { get; set; }
        public string hovedkategori { get; set; }
        public string underkategori { get; set; }
    }
}
