//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class person
    {
        public string cristinID { get; set; }
        public string fornavn { get; set; }
        public string etternavn { get; set; }
    
        public virtual rank rank { get; set; }
    }
}
