//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ForskningApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class aarliginstitusjonsranking2015
    {
        public string cristinID { get; set; }
        public int rankPoeng { get; set; }
        public double poeng { get; set; }
        public Nullable<int> rankPublikasjoner { get; set; }
        public Nullable<double> publikasjoner { get; set; }
        public int rankKroner { get; set; }
        public double kroner { get; set; }
        public Nullable<int> niva2 { get; set; }
        public Nullable<int> rankniva2 { get; set; }
    }
}
