//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ForskningApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class rankinstitusjon
    {
        public string cristinID { get; set; }
        public double poeng { get; set; }
        public double poengNytt { get; set; }
        public int rank { get; set; }
        public int rankNytt { get; set; }
        public Nullable<double> kroner { get; set; }
        public Nullable<int> publikasjoner { get; set; }
        public Nullable<int> niva2 { get; set; }
    }
}
