//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ForskningApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tidsskrift
    {
        public string cristinID { get; set; }
        public string navn { get; set; }
        public string issn { get; set; }
        public string url { get; set; }
        public string kvalitet { get; set; }
    }
}
