//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ForskningApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tilhorighet
    {
        public int tilhorighetsID { get; set; }
        public string cristinID { get; set; }
        public string institusjon { get; set; }
        public string institutt { get; set; }
        public string posisjon { get; set; }
        public short aktiv { get; set; }
    }
}
